sudo: false
cache: yarn
language: node_js
node_js:
  - 6.9.2
before_install:
  - npm install -g yarn@0.27.5
script:
  - yarn test
after_success:
  - bash scripts/deploy-docs-examples.sh
notifications:
  email:
    on_success: never
    on_failure: change
env:
  global:
    secure: lcdjTpuv2imFSgcYWMLV4odyZ4jOTjJhyViGg9hOFzggoPGFAjplz6bPgNJsxq20ZsFDw4UN6UlZ8lPGlByIUBhf2OXs0cEJDcNSoYAV7CuTMSdZsLDb+TrWQvjtSZMBEkeVENfJjyfiJo7PCt2/cIQXSVSnhZ5Uiir+Eus5x/s=
