cache: false
language: node_js
node_js:
  - "6.9.2"

install:
  - npm install

before_script:
  - cp secrets.example.json secrets.json
  - npm install -g grunt-cli
  - chmod +x ./scripts/deploy-to-gh-pages.sh

script:
  - grunt test

after_success:
  - ./scripts/deploy-to-gh-pages.sh

notifications:
  email:
    on_success: never
    on_failure: change
